name: Deploy Master to Amazon ECS

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      cluster: 'C_ShareTwin_Master'
      task: 'TD_ShareTwin_Master'
      router_image: 'ghcr.io/geode-solutions/opengeodeweb-router:master'
      router_logs: '/ecs/TD_ShareTwin_Master/router/'
      viewer_image: 'ghcr.io/geode-solutions/sharetwin-viewer:master'
      viewer_logs: '/ecs/TD_ShareTwin_Master/viewer/'
      geode_image: 'ghcr.io/geode-solutions/sharetwin-geode:master'
      geode_logs: '/ecs/TD_ShareTwin_Master/geode/'
      memory: '4096'
      cpu: '2048'
    secrets: inherit
