name: Deploy Master to Amazon ECS

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      cluster: 'C_ShareTwin_Prod'
      task: 'TD_ShareTwin_Prod'
      router_image: 'ghcr.io/geode-solutions/sharetwin_router:master'
      router_logs: '/ecs/TD_ShareTwin_Prod/router/'
      viewer_image: 'ghcr.io/geode-solutions/sharetwin_viewer:master'
      viewer_logs: '/ecs/TD_ShareTwin_Prod/viewer/'
      geode_image: 'ghcr.io/geode-solutions/sharetwin_geode:master'
      geode_logs: '/ecs/TD_ShareTwin_Prod/geode/'
      memory: '4096'
      cpu: '2048'
    secrets: inherit
