name: Deploy Dev to Amazon ECS

on:
  push:
    branches: develop

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      traefik_image: 'traefik'
      geode_image: 'ghcr.io/geode-solutions/visualization_geodebackend:develop'
      viewer_image: 'ghcr.io/geode-solutions/visualization_backend:develop'
      traefik_logs: '/ecs/TD_ShareTwin_Dev/traefik/'
      geode_logs: '/ecs/TD_ShareTwin_Dev/geode/'
      viewer_logs: '/ecs/TD_ShareTwin_Dev/viewer/'
      task: 'TD_ShareTwin_Dev'
      cluster: 'C_ShareTwin_Dev'
    secrets: inherit

