name: Deploy Dev to Amazon ECS

on:
  push:
    branches: develop

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      cluster: 'C_ShareTwin_Dev'
      task: 'TD_ShareTwin_Dev'
      router_image: '622060531233.dkr.ecr.eu-west-3.amazonaws.com/sharetwin_router:develop'
      router_logs: '/ecs/TD_ShareTwin_Dev/router/'
      viewer_image: '622060531233.dkr.ecr.eu-west-3.amazonaws.com/sharetwin_viewer:develop'
      viewer_logs: '/ecs/TD_ShareTwin_Dev/viewer/'
      geode_image: '622060531233.dkr.ecr.eu-west-3.amazonaws.com/sharetwin_geode:develop'
      geode_logs: '/ecs/TD_ShareTwin_Dev/geode/'
      memory: '4096'
      cpu: '2048'
    secrets: inherit

