name: Deploy Dev to Amazon ECS

on:
  push:
    branches: develop

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow.yml
    with:
      cluster: 'C_ShareTwin_Dev'
      task: 'TD_ShareTwin_Dev'
      traefik_image: 'traefik'
      traefik_logs: '/ecs/TD_ShareTwin_Dev/traefik/'
      viewer_image: 'ghcr.io/geode-solutions/sharetwin_viewer:develop'
      viewer_logs: '/ecs/TD_ShareTwin_Dev/viewer/'
      geode_image: 'ghcr.io/geode-solutions/sharetwin_geode:develop'
      geode_logs: '/ecs/TD_ShareTwin_Dev/geode/'
      memory: '2048'
      cpu: '1024'
    secrets: inherit

